name: CI

on: [push, pull_request]

jobs:
  testsuite:
    name: Unittests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.3']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, json, fileinfo
        tools: pecl
        coverage: pcov

    - name: Composer install
      run: |
        if [[ ${{ matrix.prefer-lowest == 'prefer-lowest' }} ]]; then
          composer update --prefer-lowest --prefer-stable
        else
          composer install && composer why-not aws/aws-sdk-php 3.286.1
        fi

    - name: Run PHPUnit
      run: |
        if [[ ${{ matrix.php-version }} == '8.1' ]]; then
          vendor/bin/phpunit --coverage-clover=coverage.xml
        else
          vendor/bin/phpunit
        fi

    - name: Code Coverage Report
      if: success() && matrix.php-version == '8.1'
      uses: codecov/codecov-action@v3

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, json, fileinfo
        coverage: none
        tools: pecl

    - name: Composer install
      run: composer update --prefer-stable

    - name: Run phpcs
      run: vendor/bin/phpcs --version && bin/phpcs --report=checkstyle

    - name: Run phpstan
      run: vendor/bin/phpstan -V && vendor/bin/phpstan analyze --error-format=github
