name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  testsuite:
    name: Unittests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.3']
        dependencies: ['highest']
        include:
            - php-version: '8.1'
              dependencies: 'lowest'
            - php-version: '8.3'
              dependencies: 'highest'

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, json, fileinfo
        tools: pecl
        coverage: pcov

    - name: Composer install
      uses: ramsey/composer-install@v2
      with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: ${{ matrix.composer-options }}

    - name: Run PHPUnit
      run: |
        if [[ ${{ matrix.php-version }} == '8.1' ]]; then
          vendor/bin/phpunit --coverage-clover=coverage.xml
        else
          vendor/bin/phpunit
        fi

    - name: Code Coverage Report
      if: success() && matrix.php-version == '8.1'
      uses: codecov/codecov-action@v3

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, json, fileinfo
        coverage: none
        tools: pecl, cs2pr

    - name: Composer install
      run: composer install

    - name: Run phpcs
      run: vendor/bin/phpcs --version && vendor/bin/phpcs --report=checkstyle | cs2pr

    - name: Run phpstan
      run: vendor/bin/phpstan -V && vendor/bin/phpstan analyze --error-format=github
